/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ActWorthyIcons
///      fonts:
///       - asset: fonts/ActWorthyIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

/// The ActWorthyIcons.icon_name can be used to access an icon
class ActWorthyIcons {
  ActWorthyIcons._();

  static const _kFontFam = 'ActWorthyIcons';

  static const IconData threeD_rotation =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ac_unit = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData access_alarm =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData access_alarms =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData access_time =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData accessibility =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData accessible =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData account_balance =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData account_box =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData account_circle =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData adb = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData add_a_photo =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData add_alarm =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData add_alert =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData add_box = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData add_circle =
      const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData add_circle_outline =
      const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData add_location =
      const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData add_shopping_cart =
      const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData add_to_photos =
      const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData add_to_queue =
      const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData adjust = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData airline_seat_flat =
      const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData airline_seat_flat_angled =
      const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData airline_seat_individual_suite =
      const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData airline_seat_legroom_extra =
      const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData airline_seat_legroom_normal =
      const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData airline_seat_legroom_reduced =
      const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData airline_seat_recline_extra =
      const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData airline_seat_recline_normal =
      const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData airplanemode_active =
      const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData airplanemode_inactive =
      const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData airplay = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData airport_shuttle =
      const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData alarm_add =
      const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData alarm_off =
      const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData alarm_on =
      const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData album = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData all_inclusive =
      const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData all_out = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData android = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData announcement =
      const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData apps = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData archive = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData arrow_back =
      const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData arrow_downward =
      const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData arrow_drop_down =
      const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData arrow_drop_down_circle =
      const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData arrow_drop_up =
      const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData arrow_forward =
      const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData arrow_upward =
      const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData art_track =
      const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData aspect_ratio =
      const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData assessment =
      const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData assignment =
      const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData assignment_ind =
      const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData assignment_late =
      const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData assignment_return =
      const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData assignment_returned =
      const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData assignment_turned_in =
      const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData assistant =
      const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData assistant_photo =
      const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData attach_file =
      const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData attach_money =
      const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData attachment =
      const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData audiotrack =
      const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData autorenew =
      const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData av_timer =
      const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData backspace =
      const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData backup = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData battery_alert =
      const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData battery_charging_full =
      const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData battery_full =
      const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData battery_std =
      const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData battery_unknown =
      const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData beach_access =
      const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData beenhere =
      const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData block = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData bluetooth =
      const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData bluetooth_audio =
      const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData bluetooth_connected =
      const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData bluetooth_disabled =
      const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData bluetooth_searching =
      const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData blur_circular =
      const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData blur_linear =
      const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData blur_off =
      const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData blur_on = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData bookmark =
      const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData bookmark_border =
      const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData border_all =
      const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData border_bottom =
      const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData border_clear =
      const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData border_color =
      const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData border_horizontal =
      const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData border_inner =
      const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData border_left =
      const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData border_outer =
      const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData border_right =
      const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData border_style =
      const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData border_top =
      const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData border_vertical =
      const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData branding_watermark =
      const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData brightness_1 =
      const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData brightness_2 =
      const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData brightness_3 =
      const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData brightness_4 =
      const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData brightness_5 =
      const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData brightness_6 =
      const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData brightness_7 =
      const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData brightness_auto =
      const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData brightness_high =
      const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData brightness_low =
      const IconData(0xe872, fontFamily: _kFontFam);
  static const IconData brightness_medium =
      const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData broken_image =
      const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData brush = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData bubble_chart =
      const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData bug_report =
      const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData build = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData burst_mode =
      const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData business =
      const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData business_center =
      const IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData cached = const IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData cake = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData call = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData call_end =
      const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData call_made =
      const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData call_merge =
      const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData call_missed =
      const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData call_missed_outgoing =
      const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData call_received =
      const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData call_split =
      const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData call_to_action =
      const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData camera_alt =
      const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData camera_enhance =
      const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData camera_front =
      const IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData camera_rear =
      const IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData camera_roll =
      const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData card_giftcard =
      const IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData card_membership =
      const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData card_travel =
      const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData casino = const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData cast = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData cast_connected =
      const IconData(0xe893, fontFamily: _kFontFam);
  static const IconData center_focus_strong =
      const IconData(0xe894, fontFamily: _kFontFam);
  static const IconData center_focus_weak =
      const IconData(0xe895, fontFamily: _kFontFam);
  static const IconData change_history =
      const IconData(0xe896, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe897, fontFamily: _kFontFam);
  static const IconData chat_bubble =
      const IconData(0xe898, fontFamily: _kFontFam);
  static const IconData chat_bubble_outline =
      const IconData(0xe899, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData check_box =
      const IconData(0xe89b, fontFamily: _kFontFam);
  static const IconData check_box_outline_blank =
      const IconData(0xe89c, fontFamily: _kFontFam);
  static const IconData check_circle =
      const IconData(0xe89d, fontFamily: _kFontFam);
  static const IconData chevron_left =
      const IconData(0xe89e, fontFamily: _kFontFam);
  static const IconData chevron_right =
      const IconData(0xe89f, fontFamily: _kFontFam);
  static const IconData child_care =
      const IconData(0xe8a0, fontFamily: _kFontFam);
  static const IconData child_friendly =
      const IconData(0xe8a1, fontFamily: _kFontFam);
  static const IconData chrome_reader_mode =
      const IconData(0xe8a2, fontFamily: _kFontFam);
  static const IconData class_icon =
      const IconData(0xe8a3, fontFamily: _kFontFam);
  static const IconData clear = const IconData(0xe8a4, fontFamily: _kFontFam);
  static const IconData clear_all =
      const IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe8a6, fontFamily: _kFontFam);
  static const IconData closed_caption =
      const IconData(0xe8a7, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData cloud_circle =
      const IconData(0xe8a9, fontFamily: _kFontFam);
  static const IconData cloud_done =
      const IconData(0xe8aa, fontFamily: _kFontFam);
  static const IconData cloud_download =
      const IconData(0xe8ab, fontFamily: _kFontFam);
  static const IconData cloud_off =
      const IconData(0xe8ac, fontFamily: _kFontFam);
  static const IconData cloud_queue =
      const IconData(0xe8ad, fontFamily: _kFontFam);
  static const IconData cloud_upload =
      const IconData(0xe8ae, fontFamily: _kFontFam);
  static const IconData code = const IconData(0xe8af, fontFamily: _kFontFam);
  static const IconData collections =
      const IconData(0xe8b0, fontFamily: _kFontFam);
  static const IconData collections_bookmark =
      const IconData(0xe8b1, fontFamily: _kFontFam);
  static const IconData color_lens =
      const IconData(0xe8b2, fontFamily: _kFontFam);
  static const IconData colorize =
      const IconData(0xe8b3, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe8b4, fontFamily: _kFontFam);
  static const IconData compare = const IconData(0xe8b5, fontFamily: _kFontFam);
  static const IconData compare_arrows =
      const IconData(0xe8b6, fontFamily: _kFontFam);
  static const IconData computer =
      const IconData(0xe8b7, fontFamily: _kFontFam);
  static const IconData confirmation_number =
      const IconData(0xe8b8, fontFamily: _kFontFam);
  static const IconData contact_mail =
      const IconData(0xe8b9, fontFamily: _kFontFam);
  static const IconData contact_phone =
      const IconData(0xe8ba, fontFamily: _kFontFam);
  static const IconData contacts =
      const IconData(0xe8bb, fontFamily: _kFontFam);
  static const IconData content_copy =
      const IconData(0xe8bc, fontFamily: _kFontFam);
  static const IconData content_cut =
      const IconData(0xe8bd, fontFamily: _kFontFam);
  static const IconData content_paste =
      const IconData(0xe8be, fontFamily: _kFontFam);
  static const IconData control_point =
      const IconData(0xe8bf, fontFamily: _kFontFam);
  static const IconData control_point_duplicate =
      const IconData(0xe8c0, fontFamily: _kFontFam);
  static const IconData copyright =
      const IconData(0xe8c1, fontFamily: _kFontFam);
  static const IconData create = const IconData(0xe8c2, fontFamily: _kFontFam);
  static const IconData create_new_folder =
      const IconData(0xe8c3, fontFamily: _kFontFam);
  static const IconData credit_card =
      const IconData(0xe8c4, fontFamily: _kFontFam);
  static const IconData crop = const IconData(0xe8c5, fontFamily: _kFontFam);
  static const IconData crop_16_9 =
      const IconData(0xe8c6, fontFamily: _kFontFam);
  static const IconData crop_3_2 =
      const IconData(0xe8c7, fontFamily: _kFontFam);
  static const IconData crop_5_4 =
      const IconData(0xe8c8, fontFamily: _kFontFam);
  static const IconData crop_7_5 =
      const IconData(0xe8c9, fontFamily: _kFontFam);
  static const IconData crop_din =
      const IconData(0xe8ca, fontFamily: _kFontFam);
  static const IconData crop_free =
      const IconData(0xe8cb, fontFamily: _kFontFam);
  static const IconData crop_landscape =
      const IconData(0xe8cc, fontFamily: _kFontFam);
  static const IconData crop_original =
      const IconData(0xe8cd, fontFamily: _kFontFam);
  static const IconData crop_portrait =
      const IconData(0xe8ce, fontFamily: _kFontFam);
  static const IconData crop_rotate =
      const IconData(0xe8cf, fontFamily: _kFontFam);
  static const IconData crop_square =
      const IconData(0xe8d0, fontFamily: _kFontFam);
  static const IconData dashboard =
      const IconData(0xe8d1, fontFamily: _kFontFam);
  static const IconData data_usage =
      const IconData(0xe8d2, fontFamily: _kFontFam);
  static const IconData date_range =
      const IconData(0xe8d3, fontFamily: _kFontFam);
  static const IconData dehaze = const IconData(0xe8d4, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe8d5, fontFamily: _kFontFam);
  static const IconData delete_forever =
      const IconData(0xe8d6, fontFamily: _kFontFam);
  static const IconData delete_sweep =
      const IconData(0xe8d7, fontFamily: _kFontFam);
  static const IconData description =
      const IconData(0xe8d8, fontFamily: _kFontFam);
  static const IconData desktop_mac =
      const IconData(0xe8d9, fontFamily: _kFontFam);
  static const IconData desktop_windows =
      const IconData(0xe8da, fontFamily: _kFontFam);
  static const IconData details = const IconData(0xe8db, fontFamily: _kFontFam);
  static const IconData developer_board =
      const IconData(0xe8dc, fontFamily: _kFontFam);
  static const IconData developer_mode =
      const IconData(0xe8dd, fontFamily: _kFontFam);
  static const IconData device_hub =
      const IconData(0xe8de, fontFamily: _kFontFam);
  static const IconData devices = const IconData(0xe8df, fontFamily: _kFontFam);
  static const IconData devices_other =
      const IconData(0xe8e0, fontFamily: _kFontFam);
  static const IconData dialer_sip =
      const IconData(0xe8e1, fontFamily: _kFontFam);
  static const IconData dialpad = const IconData(0xe8e2, fontFamily: _kFontFam);
  static const IconData directions =
      const IconData(0xe8e3, fontFamily: _kFontFam);
  static const IconData directions_bike =
      const IconData(0xe8e4, fontFamily: _kFontFam);
  static const IconData directions_boat =
      const IconData(0xe8e5, fontFamily: _kFontFam);
  static const IconData directions_bus =
      const IconData(0xe8e6, fontFamily: _kFontFam);
  static const IconData directions_car =
      const IconData(0xe8e7, fontFamily: _kFontFam);
  static const IconData directions_railway =
      const IconData(0xe8e8, fontFamily: _kFontFam);
  static const IconData directions_run =
      const IconData(0xe8e9, fontFamily: _kFontFam);
  static const IconData directions_subway =
      const IconData(0xe8ea, fontFamily: _kFontFam);
  static const IconData directions_transit =
      const IconData(0xe8eb, fontFamily: _kFontFam);
  static const IconData directions_walk =
      const IconData(0xe8ec, fontFamily: _kFontFam);
  static const IconData disc_full =
      const IconData(0xe8ed, fontFamily: _kFontFam);
  static const IconData dns = const IconData(0xe8ee, fontFamily: _kFontFam);
  static const IconData do_not_disturb =
      const IconData(0xe8ef, fontFamily: _kFontFam);
  static const IconData do_not_disturb_alt =
      const IconData(0xe8f0, fontFamily: _kFontFam);
  static const IconData do_not_disturb_off =
      const IconData(0xe8f1, fontFamily: _kFontFam);
  static const IconData do_not_disturb_on =
      const IconData(0xe8f2, fontFamily: _kFontFam);
  static const IconData dock = const IconData(0xe8f3, fontFamily: _kFontFam);
  static const IconData domain = const IconData(0xe8f4, fontFamily: _kFontFam);
  static const IconData done = const IconData(0xe8f5, fontFamily: _kFontFam);
  static const IconData done_all =
      const IconData(0xe8f6, fontFamily: _kFontFam);
  static const IconData donut_large =
      const IconData(0xe8f7, fontFamily: _kFontFam);
  static const IconData donut_small =
      const IconData(0xe8f8, fontFamily: _kFontFam);
  static const IconData drafts = const IconData(0xe8f9, fontFamily: _kFontFam);
  static const IconData drag_handle =
      const IconData(0xe8fa, fontFamily: _kFontFam);
  static const IconData drive_eta =
      const IconData(0xe8fb, fontFamily: _kFontFam);
  static const IconData dvr = const IconData(0xe8fc, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe8fd, fontFamily: _kFontFam);
  static const IconData edit_location =
      const IconData(0xe8fe, fontFamily: _kFontFam);
  static const IconData eject = const IconData(0xe8ff, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData enhanced_encryption =
      const IconData(0xe901, fontFamily: _kFontFam);
  static const IconData equalizer =
      const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData error = const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData error_outline =
      const IconData(0xe904, fontFamily: _kFontFam);
  static const IconData euro_symbol =
      const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData ev_station =
      const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData event = const IconData(0xe907, fontFamily: _kFontFam);
  static const IconData event_available =
      const IconData(0xe908, fontFamily: _kFontFam);
  static const IconData event_busy =
      const IconData(0xe909, fontFamily: _kFontFam);
  static const IconData event_note =
      const IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData event_seat =
      const IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData exit_to_app =
      const IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData expand_less =
      const IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData expand_more =
      const IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData explicit =
      const IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData explore = const IconData(0xe910, fontFamily: _kFontFam);
  static const IconData exposure =
      const IconData(0xe911, fontFamily: _kFontFam);
  static const IconData exposure_neg_1 =
      const IconData(0xe912, fontFamily: _kFontFam);
  static const IconData exposure_neg_2 =
      const IconData(0xe913, fontFamily: _kFontFam);
  static const IconData exposure_plus_1 =
      const IconData(0xe914, fontFamily: _kFontFam);
  static const IconData exposure_plus_2 =
      const IconData(0xe915, fontFamily: _kFontFam);
  static const IconData exposure_zero =
      const IconData(0xe916, fontFamily: _kFontFam);
  static const IconData extension =
      const IconData(0xe917, fontFamily: _kFontFam);
  static const IconData face = const IconData(0xe918, fontFamily: _kFontFam);
  static const IconData fast_forward =
      const IconData(0xe919, fontFamily: _kFontFam);
  static const IconData fast_rewind =
      const IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData favorite =
      const IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData favorite_border =
      const IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData featured_play_list =
      const IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData featured_video =
      const IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData feedback =
      const IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData fiber_dvr =
      const IconData(0xe920, fontFamily: _kFontFam);
  static const IconData fiber_manual_record =
      const IconData(0xe921, fontFamily: _kFontFam);
  static const IconData fiber_new =
      const IconData(0xe922, fontFamily: _kFontFam);
  static const IconData fiber_pin =
      const IconData(0xe923, fontFamily: _kFontFam);
  static const IconData fiber_smart_record =
      const IconData(0xe924, fontFamily: _kFontFam);
  static const IconData file_download =
      const IconData(0xe925, fontFamily: _kFontFam);
  static const IconData file_upload =
      const IconData(0xe926, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe927, fontFamily: _kFontFam);
  static const IconData filter_1 =
      const IconData(0xe928, fontFamily: _kFontFam);
  static const IconData filter_2 =
      const IconData(0xe929, fontFamily: _kFontFam);
  static const IconData filter_3 =
      const IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData filter_4 =
      const IconData(0xe92b, fontFamily: _kFontFam);
  static const IconData filter_5 =
      const IconData(0xe92c, fontFamily: _kFontFam);
  static const IconData filter_6 =
      const IconData(0xe92d, fontFamily: _kFontFam);
  static const IconData filter_7 =
      const IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData filter_8 =
      const IconData(0xe92f, fontFamily: _kFontFam);
  static const IconData filter_9 =
      const IconData(0xe930, fontFamily: _kFontFam);
  static const IconData filter_9_plus =
      const IconData(0xe931, fontFamily: _kFontFam);
  static const IconData filter_b_and_w =
      const IconData(0xe932, fontFamily: _kFontFam);
  static const IconData filter_center_focus =
      const IconData(0xe933, fontFamily: _kFontFam);
  static const IconData filter_drama =
      const IconData(0xe934, fontFamily: _kFontFam);
  static const IconData filter_frames =
      const IconData(0xe935, fontFamily: _kFontFam);
  static const IconData filter_hdr =
      const IconData(0xe936, fontFamily: _kFontFam);
  static const IconData filter_list =
      const IconData(0xe937, fontFamily: _kFontFam);
  static const IconData filter_none =
      const IconData(0xe938, fontFamily: _kFontFam);
  static const IconData filter_tilt_shift =
      const IconData(0xe939, fontFamily: _kFontFam);
  static const IconData filter_vintage =
      const IconData(0xe93a, fontFamily: _kFontFam);
  static const IconData find_in_page =
      const IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData find_replace =
      const IconData(0xe93c, fontFamily: _kFontFam);
  static const IconData fingerprint =
      const IconData(0xe93d, fontFamily: _kFontFam);
  static const IconData first_page =
      const IconData(0xe93e, fontFamily: _kFontFam);
  static const IconData fitness_center =
      const IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xe940, fontFamily: _kFontFam);
  static const IconData flare = const IconData(0xe941, fontFamily: _kFontFam);
  static const IconData flash_auto =
      const IconData(0xe942, fontFamily: _kFontFam);
  static const IconData flash_off =
      const IconData(0xe943, fontFamily: _kFontFam);
  static const IconData flash_on =
      const IconData(0xe944, fontFamily: _kFontFam);
  static const IconData flight = const IconData(0xe945, fontFamily: _kFontFam);
  static const IconData flight_land =
      const IconData(0xe946, fontFamily: _kFontFam);
  static const IconData flight_takeoff =
      const IconData(0xe947, fontFamily: _kFontFam);
  static const IconData flip = const IconData(0xe948, fontFamily: _kFontFam);
  static const IconData flip_to_back =
      const IconData(0xe949, fontFamily: _kFontFam);
  static const IconData flip_to_front =
      const IconData(0xe94a, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe94b, fontFamily: _kFontFam);
  static const IconData folder_open =
      const IconData(0xe94c, fontFamily: _kFontFam);
  static const IconData folder_shared =
      const IconData(0xe94d, fontFamily: _kFontFam);
  static const IconData folder_special =
      const IconData(0xe94e, fontFamily: _kFontFam);
  static const IconData font_download =
      const IconData(0xe94f, fontFamily: _kFontFam);
  static const IconData format_align_center =
      const IconData(0xe950, fontFamily: _kFontFam);
  static const IconData format_align_justify =
      const IconData(0xe951, fontFamily: _kFontFam);
  static const IconData format_align_left =
      const IconData(0xe952, fontFamily: _kFontFam);
  static const IconData format_align_right =
      const IconData(0xe953, fontFamily: _kFontFam);
  static const IconData format_bold =
      const IconData(0xe954, fontFamily: _kFontFam);
  static const IconData format_clear =
      const IconData(0xe955, fontFamily: _kFontFam);
  static const IconData format_color_fill =
      const IconData(0xe956, fontFamily: _kFontFam);
  static const IconData format_color_reset =
      const IconData(0xe957, fontFamily: _kFontFam);
  static const IconData format_color_text =
      const IconData(0xe958, fontFamily: _kFontFam);
  static const IconData format_indent_decrease =
      const IconData(0xe959, fontFamily: _kFontFam);
  static const IconData format_indent_increase =
      const IconData(0xe95a, fontFamily: _kFontFam);
  static const IconData format_italic =
      const IconData(0xe95b, fontFamily: _kFontFam);
  static const IconData format_line_spacing =
      const IconData(0xe95c, fontFamily: _kFontFam);
  static const IconData format_list_bulleted =
      const IconData(0xe95d, fontFamily: _kFontFam);
  static const IconData format_list_numbered =
      const IconData(0xe95e, fontFamily: _kFontFam);
  static const IconData format_paint =
      const IconData(0xe95f, fontFamily: _kFontFam);
  static const IconData format_quote =
      const IconData(0xe960, fontFamily: _kFontFam);
  static const IconData format_shapes =
      const IconData(0xe961, fontFamily: _kFontFam);
  static const IconData format_size =
      const IconData(0xe962, fontFamily: _kFontFam);
  static const IconData format_strikethrough =
      const IconData(0xe963, fontFamily: _kFontFam);
  static const IconData format_textdirection_l_to_r =
      const IconData(0xe964, fontFamily: _kFontFam);
  static const IconData format_textdirection_r_to_l =
      const IconData(0xe965, fontFamily: _kFontFam);
  static const IconData format_underlined =
      const IconData(0xe966, fontFamily: _kFontFam);
  static const IconData forum = const IconData(0xe967, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe968, fontFamily: _kFontFam);
  static const IconData forward_10 =
      const IconData(0xe969, fontFamily: _kFontFam);
  static const IconData forward_30 =
      const IconData(0xe96a, fontFamily: _kFontFam);
  static const IconData forward_5 =
      const IconData(0xe96b, fontFamily: _kFontFam);
  static const IconData free_breakfast =
      const IconData(0xe96c, fontFamily: _kFontFam);
  static const IconData fullscreen =
      const IconData(0xe96d, fontFamily: _kFontFam);
  static const IconData fullscreen_exit =
      const IconData(0xe96e, fontFamily: _kFontFam);
  static const IconData functions =
      const IconData(0xe96f, fontFamily: _kFontFam);
  static const IconData g_translate =
      const IconData(0xe970, fontFamily: _kFontFam);
  static const IconData gamepad = const IconData(0xe971, fontFamily: _kFontFam);
  static const IconData games = const IconData(0xe972, fontFamily: _kFontFam);
  static const IconData gavel = const IconData(0xe973, fontFamily: _kFontFam);
  static const IconData gesture = const IconData(0xe974, fontFamily: _kFontFam);
  static const IconData get_app = const IconData(0xe975, fontFamily: _kFontFam);
  static const IconData gif = const IconData(0xe976, fontFamily: _kFontFam);
  static const IconData goat = const IconData(0xe977, fontFamily: _kFontFam);
  static const IconData golf_course =
      const IconData(0xe978, fontFamily: _kFontFam);
  static const IconData gps_fixed =
      const IconData(0xe979, fontFamily: _kFontFam);
  static const IconData gps_not_fixed =
      const IconData(0xe97a, fontFamily: _kFontFam);
  static const IconData gps_off = const IconData(0xe97b, fontFamily: _kFontFam);
  static const IconData grade = const IconData(0xe97c, fontFamily: _kFontFam);
  static const IconData gradient =
      const IconData(0xe97d, fontFamily: _kFontFam);
  static const IconData grain = const IconData(0xe97e, fontFamily: _kFontFam);
  static const IconData graphic_eq =
      const IconData(0xe97f, fontFamily: _kFontFam);
  static const IconData grid_off =
      const IconData(0xe980, fontFamily: _kFontFam);
  static const IconData grid_on = const IconData(0xe981, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe982, fontFamily: _kFontFam);
  static const IconData group_add =
      const IconData(0xe983, fontFamily: _kFontFam);
  static const IconData group_work =
      const IconData(0xe984, fontFamily: _kFontFam);
  static const IconData hd = const IconData(0xe985, fontFamily: _kFontFam);
  static const IconData hdr_off = const IconData(0xe986, fontFamily: _kFontFam);
  static const IconData hdr_on = const IconData(0xe987, fontFamily: _kFontFam);
  static const IconData hdr_strong =
      const IconData(0xe988, fontFamily: _kFontFam);
  static const IconData hdr_weak =
      const IconData(0xe989, fontFamily: _kFontFam);
  static const IconData headset = const IconData(0xe98a, fontFamily: _kFontFam);
  static const IconData headset_mic =
      const IconData(0xe98b, fontFamily: _kFontFam);
  static const IconData healing = const IconData(0xe98c, fontFamily: _kFontFam);
  static const IconData hearing = const IconData(0xe98d, fontFamily: _kFontFam);
  static const IconData help = const IconData(0xe98e, fontFamily: _kFontFam);
  static const IconData help_outline =
      const IconData(0xe98f, fontFamily: _kFontFam);
  static const IconData high_quality =
      const IconData(0xe990, fontFamily: _kFontFam);
  static const IconData highlight =
      const IconData(0xe991, fontFamily: _kFontFam);
  static const IconData highlight_off =
      const IconData(0xe992, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe993, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe994, fontFamily: _kFontFam);
  static const IconData hot_tub = const IconData(0xe995, fontFamily: _kFontFam);
  static const IconData hotel = const IconData(0xe996, fontFamily: _kFontFam);
  static const IconData hourglass_empty =
      const IconData(0xe997, fontFamily: _kFontFam);
  static const IconData hourglass_full =
      const IconData(0xe998, fontFamily: _kFontFam);
  static const IconData http = const IconData(0xe999, fontFamily: _kFontFam);
  static const IconData https = const IconData(0xe99a, fontFamily: _kFontFam);
  static const IconData image = const IconData(0xe99b, fontFamily: _kFontFam);
  static const IconData image_aspect_ratio =
      const IconData(0xe99c, fontFamily: _kFontFam);
  static const IconData import_contacts =
      const IconData(0xe99d, fontFamily: _kFontFam);
  static const IconData import_export =
      const IconData(0xe99e, fontFamily: _kFontFam);
  static const IconData important_devices =
      const IconData(0xe99f, fontFamily: _kFontFam);
  static const IconData inbox = const IconData(0xe9a0, fontFamily: _kFontFam);
  static const IconData indeterminate_check_box =
      const IconData(0xe9a1, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe9a2, fontFamily: _kFontFam);
  static const IconData info_outline =
      const IconData(0xe9a3, fontFamily: _kFontFam);
  static const IconData input = const IconData(0xe9a4, fontFamily: _kFontFam);
  static const IconData insert_chart =
      const IconData(0xe9a5, fontFamily: _kFontFam);
  static const IconData insert_comment =
      const IconData(0xe9a6, fontFamily: _kFontFam);
  static const IconData insert_drive_file =
      const IconData(0xe9a7, fontFamily: _kFontFam);
  static const IconData insert_emoticon =
      const IconData(0xe9a8, fontFamily: _kFontFam);
  static const IconData insert_invitation =
      const IconData(0xe9a9, fontFamily: _kFontFam);
  static const IconData insert_link =
      const IconData(0xe9aa, fontFamily: _kFontFam);
  static const IconData insert_photo =
      const IconData(0xe9ab, fontFamily: _kFontFam);
  static const IconData invert_colors =
      const IconData(0xe9ac, fontFamily: _kFontFam);
  static const IconData invert_colors_off =
      const IconData(0xe9ad, fontFamily: _kFontFam);
  static const IconData iso = const IconData(0xe9ae, fontFamily: _kFontFam);
  static const IconData keyboard =
      const IconData(0xe9af, fontFamily: _kFontFam);
  static const IconData keyboard_arrow_down =
      const IconData(0xe9b0, fontFamily: _kFontFam);
  static const IconData keyboard_arrow_left =
      const IconData(0xe9b1, fontFamily: _kFontFam);
  static const IconData keyboard_arrow_right =
      const IconData(0xe9b2, fontFamily: _kFontFam);
  static const IconData keyboard_arrow_up =
      const IconData(0xe9b3, fontFamily: _kFontFam);
  static const IconData keyboard_backspace =
      const IconData(0xe9b4, fontFamily: _kFontFam);
  static const IconData keyboard_capslock =
      const IconData(0xe9b5, fontFamily: _kFontFam);
  static const IconData keyboard_hide =
      const IconData(0xe9b6, fontFamily: _kFontFam);
  static const IconData keyboard_return =
      const IconData(0xe9b7, fontFamily: _kFontFam);
  static const IconData keyboard_tab =
      const IconData(0xe9b8, fontFamily: _kFontFam);
  static const IconData keyboard_voice =
      const IconData(0xe9b9, fontFamily: _kFontFam);
  static const IconData kitchen = const IconData(0xe9ba, fontFamily: _kFontFam);
  static const IconData label = const IconData(0xe9bb, fontFamily: _kFontFam);
  static const IconData label_outline =
      const IconData(0xe9bc, fontFamily: _kFontFam);
  static const IconData landscape =
      const IconData(0xe9bd, fontFamily: _kFontFam);
  static const IconData language =
      const IconData(0xe9be, fontFamily: _kFontFam);
  static const IconData laptop = const IconData(0xe9bf, fontFamily: _kFontFam);
  static const IconData laptop_chromebook =
      const IconData(0xe9c0, fontFamily: _kFontFam);
  static const IconData laptop_mac =
      const IconData(0xe9c1, fontFamily: _kFontFam);
  static const IconData laptop_windows =
      const IconData(0xe9c2, fontFamily: _kFontFam);
  static const IconData last_page =
      const IconData(0xe9c3, fontFamily: _kFontFam);
  static const IconData launch = const IconData(0xe9c4, fontFamily: _kFontFam);
  static const IconData layers = const IconData(0xe9c5, fontFamily: _kFontFam);
  static const IconData layers_clear =
      const IconData(0xe9c6, fontFamily: _kFontFam);
  static const IconData leak_add =
      const IconData(0xe9c7, fontFamily: _kFontFam);
  static const IconData leak_remove =
      const IconData(0xe9c8, fontFamily: _kFontFam);
  static const IconData lens = const IconData(0xe9c9, fontFamily: _kFontFam);
  static const IconData library_add =
      const IconData(0xe9ca, fontFamily: _kFontFam);
  static const IconData library_books =
      const IconData(0xe9cb, fontFamily: _kFontFam);
  static const IconData library_music =
      const IconData(0xe9cc, fontFamily: _kFontFam);
  static const IconData lightbulb_outline =
      const IconData(0xe9cd, fontFamily: _kFontFam);
  static const IconData line_style =
      const IconData(0xe9ce, fontFamily: _kFontFam);
  static const IconData line_weight =
      const IconData(0xe9cf, fontFamily: _kFontFam);
  static const IconData linear_scale =
      const IconData(0xe9d0, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xe9d1, fontFamily: _kFontFam);
  static const IconData linked_camera =
      const IconData(0xe9d2, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe9d3, fontFamily: _kFontFam);
  static const IconData live_help =
      const IconData(0xe9d4, fontFamily: _kFontFam);
  static const IconData live_tv = const IconData(0xe9d5, fontFamily: _kFontFam);
  static const IconData local_activity =
      const IconData(0xe9d6, fontFamily: _kFontFam);
  static const IconData local_airport =
      const IconData(0xe9d7, fontFamily: _kFontFam);
  static const IconData local_atm =
      const IconData(0xe9d8, fontFamily: _kFontFam);
  static const IconData local_bar =
      const IconData(0xe9d9, fontFamily: _kFontFam);
  static const IconData local_cafe =
      const IconData(0xe9da, fontFamily: _kFontFam);
  static const IconData local_car_wash =
      const IconData(0xe9db, fontFamily: _kFontFam);
  static const IconData local_convenience_store =
      const IconData(0xe9dc, fontFamily: _kFontFam);
  static const IconData local_dining =
      const IconData(0xe9dd, fontFamily: _kFontFam);
  static const IconData local_drink =
      const IconData(0xe9de, fontFamily: _kFontFam);
  static const IconData local_florist =
      const IconData(0xe9df, fontFamily: _kFontFam);
  static const IconData local_gas_station =
      const IconData(0xe9e0, fontFamily: _kFontFam);
  static const IconData local_grocery_store =
      const IconData(0xe9e1, fontFamily: _kFontFam);
  static const IconData local_hospital =
      const IconData(0xe9e2, fontFamily: _kFontFam);
  static const IconData local_hotel =
      const IconData(0xe9e3, fontFamily: _kFontFam);
  static const IconData local_laundry_service =
      const IconData(0xe9e4, fontFamily: _kFontFam);
  static const IconData local_library =
      const IconData(0xe9e5, fontFamily: _kFontFam);
  static const IconData local_mall =
      const IconData(0xe9e6, fontFamily: _kFontFam);
  static const IconData local_movies =
      const IconData(0xe9e7, fontFamily: _kFontFam);
  static const IconData local_offer =
      const IconData(0xe9e8, fontFamily: _kFontFam);
  static const IconData local_parking =
      const IconData(0xe9e9, fontFamily: _kFontFam);
  static const IconData local_pharmacy =
      const IconData(0xe9ea, fontFamily: _kFontFam);
  static const IconData local_phone =
      const IconData(0xe9eb, fontFamily: _kFontFam);
  static const IconData local_pizza =
      const IconData(0xe9ec, fontFamily: _kFontFam);
  static const IconData local_play =
      const IconData(0xe9ed, fontFamily: _kFontFam);
  static const IconData local_post_office =
      const IconData(0xe9ee, fontFamily: _kFontFam);
  static const IconData local_printshop =
      const IconData(0xe9ef, fontFamily: _kFontFam);
  static const IconData local_see =
      const IconData(0xe9f0, fontFamily: _kFontFam);
  static const IconData local_shipping =
      const IconData(0xe9f1, fontFamily: _kFontFam);
  static const IconData local_taxi =
      const IconData(0xe9f2, fontFamily: _kFontFam);
  static const IconData location_city =
      const IconData(0xe9f3, fontFamily: _kFontFam);
  static const IconData location_disabled =
      const IconData(0xe9f4, fontFamily: _kFontFam);
  static const IconData location_off =
      const IconData(0xe9f5, fontFamily: _kFontFam);
  static const IconData location_on =
      const IconData(0xe9f6, fontFamily: _kFontFam);
  static const IconData location_searching =
      const IconData(0xe9f7, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe9f8, fontFamily: _kFontFam);
  static const IconData lock_open =
      const IconData(0xe9f9, fontFamily: _kFontFam);
  static const IconData lock_outline =
      const IconData(0xe9fa, fontFamily: _kFontFam);
  static const IconData looks = const IconData(0xe9fb, fontFamily: _kFontFam);
  static const IconData looks_3 = const IconData(0xe9fc, fontFamily: _kFontFam);
  static const IconData looks_4 = const IconData(0xe9fd, fontFamily: _kFontFam);
  static const IconData looks_5 = const IconData(0xe9fe, fontFamily: _kFontFam);
  static const IconData looks_6 = const IconData(0xe9ff, fontFamily: _kFontFam);
  static const IconData looks_one =
      const IconData(0xea00, fontFamily: _kFontFam);
  static const IconData looks_two =
      const IconData(0xea01, fontFamily: _kFontFam);
  static const IconData loop = const IconData(0xea02, fontFamily: _kFontFam);
  static const IconData loupe = const IconData(0xea03, fontFamily: _kFontFam);
  static const IconData low_priority =
      const IconData(0xea04, fontFamily: _kFontFam);
  static const IconData loyalty = const IconData(0xea05, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xea06, fontFamily: _kFontFam);
  static const IconData mail_outline =
      const IconData(0xea07, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xea08, fontFamily: _kFontFam);
  static const IconData markunread =
      const IconData(0xea09, fontFamily: _kFontFam);
  static const IconData markunread_mailbox =
      const IconData(0xea0a, fontFamily: _kFontFam);
  static const IconData memory = const IconData(0xea0b, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xea0c, fontFamily: _kFontFam);
  static const IconData merge_type =
      const IconData(0xea0d, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xea0e, fontFamily: _kFontFam);
  static const IconData mic = const IconData(0xea0f, fontFamily: _kFontFam);
  static const IconData mic_none =
      const IconData(0xea10, fontFamily: _kFontFam);
  static const IconData mic_off = const IconData(0xea11, fontFamily: _kFontFam);
  static const IconData mms = const IconData(0xea12, fontFamily: _kFontFam);
  static const IconData mode_comment =
      const IconData(0xea13, fontFamily: _kFontFam);
  static const IconData mode_edit =
      const IconData(0xea14, fontFamily: _kFontFam);
  static const IconData monetization_on =
      const IconData(0xea15, fontFamily: _kFontFam);
  static const IconData money_off =
      const IconData(0xea16, fontFamily: _kFontFam);
  static const IconData monochrome_photos =
      const IconData(0xea17, fontFamily: _kFontFam);
  static const IconData mood = const IconData(0xea18, fontFamily: _kFontFam);
  static const IconData mood_bad =
      const IconData(0xea19, fontFamily: _kFontFam);
  static const IconData more = const IconData(0xea1a, fontFamily: _kFontFam);
  static const IconData more_horiz =
      const IconData(0xea1b, fontFamily: _kFontFam);
  static const IconData more_vert =
      const IconData(0xea1c, fontFamily: _kFontFam);
  static const IconData motorcycle =
      const IconData(0xea1d, fontFamily: _kFontFam);
  static const IconData mouse = const IconData(0xea1e, fontFamily: _kFontFam);
  static const IconData move_to_inbox =
      const IconData(0xea1f, fontFamily: _kFontFam);
  static const IconData movie = const IconData(0xea20, fontFamily: _kFontFam);
  static const IconData movie_creation =
      const IconData(0xea21, fontFamily: _kFontFam);
  static const IconData movie_filter =
      const IconData(0xea22, fontFamily: _kFontFam);
  static const IconData multiline_chart =
      const IconData(0xea23, fontFamily: _kFontFam);
  static const IconData music_note =
      const IconData(0xea24, fontFamily: _kFontFam);
  static const IconData music_video =
      const IconData(0xea25, fontFamily: _kFontFam);
  static const IconData my_location =
      const IconData(0xea26, fontFamily: _kFontFam);
  static const IconData nature = const IconData(0xea27, fontFamily: _kFontFam);
  static const IconData nature_people =
      const IconData(0xea28, fontFamily: _kFontFam);
  static const IconData navigate_before =
      const IconData(0xea29, fontFamily: _kFontFam);
  static const IconData navigate_next =
      const IconData(0xea2a, fontFamily: _kFontFam);
  static const IconData navigation =
      const IconData(0xea2b, fontFamily: _kFontFam);
  static const IconData near_me = const IconData(0xea2c, fontFamily: _kFontFam);
  static const IconData network_cell =
      const IconData(0xea2d, fontFamily: _kFontFam);
  static const IconData network_check =
      const IconData(0xea2e, fontFamily: _kFontFam);
  static const IconData network_locked =
      const IconData(0xea2f, fontFamily: _kFontFam);
  static const IconData network_wifi =
      const IconData(0xea30, fontFamily: _kFontFam);
  static const IconData new_releases =
      const IconData(0xea31, fontFamily: _kFontFam);
  static const IconData next_week =
      const IconData(0xea32, fontFamily: _kFontFam);
  static const IconData nfc = const IconData(0xea33, fontFamily: _kFontFam);
  static const IconData no_encryption =
      const IconData(0xea34, fontFamily: _kFontFam);
  static const IconData no_sim = const IconData(0xea35, fontFamily: _kFontFam);
  static const IconData not_interested =
      const IconData(0xea36, fontFamily: _kFontFam);
  static const IconData note = const IconData(0xea37, fontFamily: _kFontFam);
  static const IconData note_add =
      const IconData(0xea38, fontFamily: _kFontFam);
  static const IconData notifications =
      const IconData(0xea39, fontFamily: _kFontFam);
  static const IconData notifications_active =
      const IconData(0xea3a, fontFamily: _kFontFam);
  static const IconData notifications_none =
      const IconData(0xea3b, fontFamily: _kFontFam);
  static const IconData notifications_off =
      const IconData(0xea3c, fontFamily: _kFontFam);
  static const IconData notifications_paused =
      const IconData(0xea3d, fontFamily: _kFontFam);
  static const IconData offline_pin =
      const IconData(0xea3e, fontFamily: _kFontFam);
  static const IconData ondemand_video =
      const IconData(0xea3f, fontFamily: _kFontFam);
  static const IconData opacity = const IconData(0xea40, fontFamily: _kFontFam);
  static const IconData open_in_browser =
      const IconData(0xea41, fontFamily: _kFontFam);
  static const IconData open_in_new =
      const IconData(0xea42, fontFamily: _kFontFam);
  static const IconData open_with =
      const IconData(0xea43, fontFamily: _kFontFam);
  static const IconData pages = const IconData(0xea44, fontFamily: _kFontFam);
  static const IconData pageview =
      const IconData(0xea45, fontFamily: _kFontFam);
  static const IconData palette = const IconData(0xea46, fontFamily: _kFontFam);
  static const IconData pan_tool =
      const IconData(0xea47, fontFamily: _kFontFam);
  static const IconData panorama =
      const IconData(0xea48, fontFamily: _kFontFam);
  static const IconData panorama_fish_eye =
      const IconData(0xea49, fontFamily: _kFontFam);
  static const IconData panorama_horizontal =
      const IconData(0xea4a, fontFamily: _kFontFam);
  static const IconData panorama_vertical =
      const IconData(0xea4b, fontFamily: _kFontFam);
  static const IconData panorama_wide_angle =
      const IconData(0xea4c, fontFamily: _kFontFam);
  static const IconData party_mode =
      const IconData(0xea4d, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xea4e, fontFamily: _kFontFam);
  static const IconData pause_circle_filled =
      const IconData(0xea4f, fontFamily: _kFontFam);
  static const IconData pause_circle_outline =
      const IconData(0xea50, fontFamily: _kFontFam);
  static const IconData payment = const IconData(0xea51, fontFamily: _kFontFam);
  static const IconData people = const IconData(0xea52, fontFamily: _kFontFam);
  static const IconData people_outline =
      const IconData(0xea53, fontFamily: _kFontFam);
  static const IconData perm_camera_mic =
      const IconData(0xea54, fontFamily: _kFontFam);
  static const IconData perm_contact_calendar =
      const IconData(0xea55, fontFamily: _kFontFam);
  static const IconData perm_data_setting =
      const IconData(0xea56, fontFamily: _kFontFam);
  static const IconData perm_device_information =
      const IconData(0xea57, fontFamily: _kFontFam);
  static const IconData perm_identity =
      const IconData(0xea58, fontFamily: _kFontFam);
  static const IconData perm_media =
      const IconData(0xea59, fontFamily: _kFontFam);
  static const IconData perm_phone_msg =
      const IconData(0xea5a, fontFamily: _kFontFam);
  static const IconData perm_scan_wifi =
      const IconData(0xea5b, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xea5c, fontFamily: _kFontFam);
  static const IconData person_add =
      const IconData(0xea5d, fontFamily: _kFontFam);
  static const IconData person_outline =
      const IconData(0xea5e, fontFamily: _kFontFam);
  static const IconData person_pin =
      const IconData(0xea5f, fontFamily: _kFontFam);
  static const IconData person_pin_circle =
      const IconData(0xea60, fontFamily: _kFontFam);
  static const IconData personal_video =
      const IconData(0xea61, fontFamily: _kFontFam);
  static const IconData pets = const IconData(0xea62, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xea63, fontFamily: _kFontFam);
  static const IconData phone_android =
      const IconData(0xea64, fontFamily: _kFontFam);
  static const IconData phone_bluetooth_speaker =
      const IconData(0xea65, fontFamily: _kFontFam);
  static const IconData phone_forwarded =
      const IconData(0xea66, fontFamily: _kFontFam);
  static const IconData phone_in_talk =
      const IconData(0xea67, fontFamily: _kFontFam);
  static const IconData phone_iphone =
      const IconData(0xea68, fontFamily: _kFontFam);
  static const IconData phone_locked =
      const IconData(0xea69, fontFamily: _kFontFam);
  static const IconData phone_missed =
      const IconData(0xea6a, fontFamily: _kFontFam);
  static const IconData phone_paused =
      const IconData(0xea6b, fontFamily: _kFontFam);
  static const IconData phonelink =
      const IconData(0xea6c, fontFamily: _kFontFam);
  static const IconData phonelink_erase =
      const IconData(0xea6d, fontFamily: _kFontFam);
  static const IconData phonelink_lock =
      const IconData(0xea6e, fontFamily: _kFontFam);
  static const IconData phonelink_off =
      const IconData(0xea6f, fontFamily: _kFontFam);
  static const IconData phonelink_ring =
      const IconData(0xea70, fontFamily: _kFontFam);
  static const IconData phonelink_setup =
      const IconData(0xea71, fontFamily: _kFontFam);
  static const IconData photo = const IconData(0xea72, fontFamily: _kFontFam);
  static const IconData photo_album =
      const IconData(0xea73, fontFamily: _kFontFam);
  static const IconData photo_camera =
      const IconData(0xea74, fontFamily: _kFontFam);
  static const IconData photo_filter =
      const IconData(0xea75, fontFamily: _kFontFam);
  static const IconData photo_library =
      const IconData(0xea76, fontFamily: _kFontFam);
  static const IconData photo_size_select_actual =
      const IconData(0xea77, fontFamily: _kFontFam);
  static const IconData photo_size_select_large =
      const IconData(0xea78, fontFamily: _kFontFam);
  static const IconData photo_size_select_small =
      const IconData(0xea79, fontFamily: _kFontFam);
  static const IconData picture_as_pdf =
      const IconData(0xea7a, fontFamily: _kFontFam);
  static const IconData picture_in_picture =
      const IconData(0xea7b, fontFamily: _kFontFam);
  static const IconData picture_in_picture_alt =
      const IconData(0xea7c, fontFamily: _kFontFam);
  static const IconData pie_chart =
      const IconData(0xea7d, fontFamily: _kFontFam);
  static const IconData pie_chart_outlined =
      const IconData(0xea7e, fontFamily: _kFontFam);
  static const IconData pin_drop =
      const IconData(0xea7f, fontFamily: _kFontFam);
  static const IconData place = const IconData(0xea80, fontFamily: _kFontFam);
  static const IconData play_arrow =
      const IconData(0xea81, fontFamily: _kFontFam);
  static const IconData play_circle_filled =
      const IconData(0xea82, fontFamily: _kFontFam);
  static const IconData play_circle_outline =
      const IconData(0xea83, fontFamily: _kFontFam);
  static const IconData play_for_work =
      const IconData(0xea84, fontFamily: _kFontFam);
  static const IconData playlist_add =
      const IconData(0xea85, fontFamily: _kFontFam);
  static const IconData playlist_add_check =
      const IconData(0xea86, fontFamily: _kFontFam);
  static const IconData playlist_play =
      const IconData(0xea87, fontFamily: _kFontFam);
  static const IconData plus_one =
      const IconData(0xea88, fontFamily: _kFontFam);
  static const IconData poll = const IconData(0xea89, fontFamily: _kFontFam);
  static const IconData polymer = const IconData(0xea8a, fontFamily: _kFontFam);
  static const IconData pool = const IconData(0xea8b, fontFamily: _kFontFam);
  static const IconData portable_wifi_off =
      const IconData(0xea8c, fontFamily: _kFontFam);
  static const IconData portrait =
      const IconData(0xea8d, fontFamily: _kFontFam);
  static const IconData power = const IconData(0xea8e, fontFamily: _kFontFam);
  static const IconData power_input =
      const IconData(0xea8f, fontFamily: _kFontFam);
  static const IconData power_settings_new =
      const IconData(0xea90, fontFamily: _kFontFam);
  static const IconData pregnant_woman =
      const IconData(0xea91, fontFamily: _kFontFam);
  static const IconData present_to_all =
      const IconData(0xea92, fontFamily: _kFontFam);
  static const IconData print = const IconData(0xea93, fontFamily: _kFontFam);
  static const IconData priority_high =
      const IconData(0xea94, fontFamily: _kFontFam);
  static const IconData public = const IconData(0xea95, fontFamily: _kFontFam);
  static const IconData publish = const IconData(0xea96, fontFamily: _kFontFam);
  static const IconData query_builder =
      const IconData(0xea97, fontFamily: _kFontFam);
  static const IconData question_answer =
      const IconData(0xea98, fontFamily: _kFontFam);
  static const IconData queue = const IconData(0xea99, fontFamily: _kFontFam);
  static const IconData queue_music =
      const IconData(0xea9a, fontFamily: _kFontFam);
  static const IconData queue_play_next =
      const IconData(0xea9b, fontFamily: _kFontFam);
  static const IconData radio = const IconData(0xea9c, fontFamily: _kFontFam);
  static const IconData radio_button_checked =
      const IconData(0xea9d, fontFamily: _kFontFam);
  static const IconData radio_button_unchecked =
      const IconData(0xea9e, fontFamily: _kFontFam);
  static const IconData rate_review =
      const IconData(0xea9f, fontFamily: _kFontFam);
  static const IconData receipt = const IconData(0xeaa0, fontFamily: _kFontFam);
  static const IconData recent_actors =
      const IconData(0xeaa1, fontFamily: _kFontFam);
  static const IconData record_voice_over =
      const IconData(0xeaa2, fontFamily: _kFontFam);
  static const IconData redeem = const IconData(0xeaa3, fontFamily: _kFontFam);
  static const IconData redo = const IconData(0xeaa4, fontFamily: _kFontFam);
  static const IconData refresh = const IconData(0xeaa5, fontFamily: _kFontFam);
  static const IconData remove = const IconData(0xeaa6, fontFamily: _kFontFam);
  static const IconData remove_circle =
      const IconData(0xeaa7, fontFamily: _kFontFam);
  static const IconData remove_circle_outline =
      const IconData(0xeaa8, fontFamily: _kFontFam);
  static const IconData remove_from_queue =
      const IconData(0xeaa9, fontFamily: _kFontFam);
  static const IconData remove_red_eye =
      const IconData(0xeaaa, fontFamily: _kFontFam);
  static const IconData remove_shopping_cart =
      const IconData(0xeaab, fontFamily: _kFontFam);
  static const IconData reorder = const IconData(0xeaac, fontFamily: _kFontFam);
  static const IconData repeat = const IconData(0xeaad, fontFamily: _kFontFam);
  static const IconData repeat_one =
      const IconData(0xeaae, fontFamily: _kFontFam);
  static const IconData replay = const IconData(0xeaaf, fontFamily: _kFontFam);
  static const IconData replay_10 =
      const IconData(0xeab0, fontFamily: _kFontFam);
  static const IconData replay_30 =
      const IconData(0xeab1, fontFamily: _kFontFam);
  static const IconData replay_5 =
      const IconData(0xeab2, fontFamily: _kFontFam);
  static const IconData reply = const IconData(0xeab3, fontFamily: _kFontFam);
  static const IconData reply_all =
      const IconData(0xeab4, fontFamily: _kFontFam);
  static const IconData report = const IconData(0xeab5, fontFamily: _kFontFam);
  static const IconData report_problem =
      const IconData(0xeab6, fontFamily: _kFontFam);
  static const IconData restaurant =
      const IconData(0xeab7, fontFamily: _kFontFam);
  static const IconData restaurant_menu =
      const IconData(0xeab8, fontFamily: _kFontFam);
  static const IconData restore = const IconData(0xeab9, fontFamily: _kFontFam);
  static const IconData restore_page =
      const IconData(0xeaba, fontFamily: _kFontFam);
  static const IconData ring_volume =
      const IconData(0xeabb, fontFamily: _kFontFam);
  static const IconData room = const IconData(0xeabc, fontFamily: _kFontFam);
  static const IconData room_service =
      const IconData(0xeabd, fontFamily: _kFontFam);
  static const IconData rotate_90_degrees_ccw =
      const IconData(0xeabe, fontFamily: _kFontFam);
  static const IconData rotate_left =
      const IconData(0xeabf, fontFamily: _kFontFam);
  static const IconData rotate_right =
      const IconData(0xeac0, fontFamily: _kFontFam);
  static const IconData rounded_corner =
      const IconData(0xeac1, fontFamily: _kFontFam);
  static const IconData router = const IconData(0xeac2, fontFamily: _kFontFam);
  static const IconData rowing = const IconData(0xeac3, fontFamily: _kFontFam);
  static const IconData rss_feed =
      const IconData(0xeac4, fontFamily: _kFontFam);
  static const IconData rv_hookup =
      const IconData(0xeac5, fontFamily: _kFontFam);
  static const IconData satellite =
      const IconData(0xeac6, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xeac7, fontFamily: _kFontFam);
  static const IconData scanner = const IconData(0xeac8, fontFamily: _kFontFam);
  static const IconData schedule =
      const IconData(0xeac9, fontFamily: _kFontFam);
  static const IconData school = const IconData(0xeaca, fontFamily: _kFontFam);
  static const IconData screen_lock_landscape =
      const IconData(0xeacb, fontFamily: _kFontFam);
  static const IconData screen_lock_portrait =
      const IconData(0xeacc, fontFamily: _kFontFam);
  static const IconData screen_lock_rotation =
      const IconData(0xeacd, fontFamily: _kFontFam);
  static const IconData screen_rotation =
      const IconData(0xeace, fontFamily: _kFontFam);
  static const IconData screen_share =
      const IconData(0xeacf, fontFamily: _kFontFam);
  static const IconData sd_card = const IconData(0xead0, fontFamily: _kFontFam);
  static const IconData sd_storage =
      const IconData(0xead1, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xead2, fontFamily: _kFontFam);
  static const IconData security =
      const IconData(0xead3, fontFamily: _kFontFam);
  static const IconData select_all =
      const IconData(0xead4, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xead5, fontFamily: _kFontFam);
  static const IconData sentiment_dissatisfied =
      const IconData(0xead6, fontFamily: _kFontFam);
  static const IconData sentiment_neutral =
      const IconData(0xead7, fontFamily: _kFontFam);
  static const IconData sentiment_satisfied =
      const IconData(0xead8, fontFamily: _kFontFam);
  static const IconData sentiment_very_dissatisfied =
      const IconData(0xead9, fontFamily: _kFontFam);
  static const IconData sentiment_very_satisfied =
      const IconData(0xeada, fontFamily: _kFontFam);
  static const IconData settings =
      const IconData(0xeadb, fontFamily: _kFontFam);
  static const IconData settings_applications =
      const IconData(0xeadc, fontFamily: _kFontFam);
  static const IconData settings_backup_restore =
      const IconData(0xeadd, fontFamily: _kFontFam);
  static const IconData settings_bluetooth =
      const IconData(0xeade, fontFamily: _kFontFam);
  static const IconData settings_brightness =
      const IconData(0xeadf, fontFamily: _kFontFam);
  static const IconData settings_cell =
      const IconData(0xeae0, fontFamily: _kFontFam);
  static const IconData settings_ethernet =
      const IconData(0xeae1, fontFamily: _kFontFam);
  static const IconData settings_input_antenna =
      const IconData(0xeae2, fontFamily: _kFontFam);
  static const IconData settings_input_component =
      const IconData(0xeae3, fontFamily: _kFontFam);
  static const IconData settings_input_composite =
      const IconData(0xeae4, fontFamily: _kFontFam);
  static const IconData settings_input_hdmi =
      const IconData(0xeae5, fontFamily: _kFontFam);
  static const IconData settings_input_svideo =
      const IconData(0xeae6, fontFamily: _kFontFam);
  static const IconData settings_overscan =
      const IconData(0xeae7, fontFamily: _kFontFam);
  static const IconData settings_phone =
      const IconData(0xeae8, fontFamily: _kFontFam);
  static const IconData settings_power =
      const IconData(0xeae9, fontFamily: _kFontFam);
  static const IconData settings_remote =
      const IconData(0xeaea, fontFamily: _kFontFam);
  static const IconData settings_system_daydream =
      const IconData(0xeaeb, fontFamily: _kFontFam);
  static const IconData settings_voice =
      const IconData(0xeaec, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xeaed, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xeaee, fontFamily: _kFontFam);
  static const IconData shop_two =
      const IconData(0xeaef, fontFamily: _kFontFam);
  static const IconData shopping_basket =
      const IconData(0xeaf0, fontFamily: _kFontFam);
  static const IconData shopping_cart =
      const IconData(0xeaf1, fontFamily: _kFontFam);
  static const IconData short_text =
      const IconData(0xeaf2, fontFamily: _kFontFam);
  static const IconData show_chart =
      const IconData(0xeaf3, fontFamily: _kFontFam);
  static const IconData shuffle = const IconData(0xeaf4, fontFamily: _kFontFam);
  static const IconData signal_cellular_4_bar =
      const IconData(0xeaf5, fontFamily: _kFontFam);
  static const IconData signal_cellular_connected_no_internet_4_bar =
      const IconData(0xeaf6, fontFamily: _kFontFam);
  static const IconData signal_cellular_no_sim =
      const IconData(0xeaf7, fontFamily: _kFontFam);
  static const IconData signal_cellular_null =
      const IconData(0xeaf8, fontFamily: _kFontFam);
  static const IconData signal_cellular_off =
      const IconData(0xeaf9, fontFamily: _kFontFam);
  static const IconData signal_wifi_4_bar =
      const IconData(0xeafa, fontFamily: _kFontFam);
  static const IconData signal_wifi_4_bar_lock =
      const IconData(0xeafb, fontFamily: _kFontFam);
  static const IconData signal_wifi_off =
      const IconData(0xeafc, fontFamily: _kFontFam);
  static const IconData sim_card =
      const IconData(0xeafd, fontFamily: _kFontFam);
  static const IconData sim_card_alert =
      const IconData(0xeafe, fontFamily: _kFontFam);
  static const IconData skip_next =
      const IconData(0xeaff, fontFamily: _kFontFam);
  static const IconData skip_previous =
      const IconData(0xeb00, fontFamily: _kFontFam);
  static const IconData slideshow =
      const IconData(0xeb01, fontFamily: _kFontFam);
  static const IconData slow_motion_video =
      const IconData(0xeb02, fontFamily: _kFontFam);
  static const IconData smartphone =
      const IconData(0xeb03, fontFamily: _kFontFam);
  static const IconData smoke_free =
      const IconData(0xeb04, fontFamily: _kFontFam);
  static const IconData smoking_rooms =
      const IconData(0xeb05, fontFamily: _kFontFam);
  static const IconData sms = const IconData(0xeb06, fontFamily: _kFontFam);
  static const IconData sms_failed =
      const IconData(0xeb07, fontFamily: _kFontFam);
  static const IconData snooze = const IconData(0xeb08, fontFamily: _kFontFam);
  static const IconData sort = const IconData(0xeb09, fontFamily: _kFontFam);
  static const IconData sort_by_alpha =
      const IconData(0xeb0a, fontFamily: _kFontFam);
  static const IconData spa = const IconData(0xeb0b, fontFamily: _kFontFam);
  static const IconData space_bar =
      const IconData(0xeb0c, fontFamily: _kFontFam);
  static const IconData speaker = const IconData(0xeb0d, fontFamily: _kFontFam);
  static const IconData speaker_group =
      const IconData(0xeb0e, fontFamily: _kFontFam);
  static const IconData speaker_notes =
      const IconData(0xeb0f, fontFamily: _kFontFam);
  static const IconData speaker_notes_off =
      const IconData(0xeb10, fontFamily: _kFontFam);
  static const IconData speaker_phone =
      const IconData(0xeb11, fontFamily: _kFontFam);
  static const IconData spellcheck =
      const IconData(0xeb12, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xeb13, fontFamily: _kFontFam);
  static const IconData star_border =
      const IconData(0xeb14, fontFamily: _kFontFam);
  static const IconData star_half =
      const IconData(0xeb15, fontFamily: _kFontFam);
  static const IconData stars = const IconData(0xeb16, fontFamily: _kFontFam);
  static const IconData stay_current_landscape =
      const IconData(0xeb17, fontFamily: _kFontFam);
  static const IconData stay_current_portrait =
      const IconData(0xeb18, fontFamily: _kFontFam);
  static const IconData stay_primary_landscape =
      const IconData(0xeb19, fontFamily: _kFontFam);
  static const IconData stay_primary_portrait =
      const IconData(0xeb1a, fontFamily: _kFontFam);
  static const IconData stop = const IconData(0xeb1b, fontFamily: _kFontFam);
  static const IconData stop_screen_share =
      const IconData(0xeb1c, fontFamily: _kFontFam);
  static const IconData storage = const IconData(0xeb1d, fontFamily: _kFontFam);
  static const IconData store = const IconData(0xeb1e, fontFamily: _kFontFam);
  static const IconData store_mall_directory =
      const IconData(0xeb1f, fontFamily: _kFontFam);
  static const IconData straighten =
      const IconData(0xeb20, fontFamily: _kFontFam);
  static const IconData streetview =
      const IconData(0xeb21, fontFamily: _kFontFam);
  static const IconData strikethrough_s =
      const IconData(0xeb22, fontFamily: _kFontFam);
  static const IconData style = const IconData(0xeb23, fontFamily: _kFontFam);
  static const IconData subdirectory_arrow_left =
      const IconData(0xeb24, fontFamily: _kFontFam);
  static const IconData subdirectory_arrow_right =
      const IconData(0xeb25, fontFamily: _kFontFam);
  static const IconData subject = const IconData(0xeb26, fontFamily: _kFontFam);
  static const IconData subscriptions =
      const IconData(0xeb27, fontFamily: _kFontFam);
  static const IconData subtitles =
      const IconData(0xeb28, fontFamily: _kFontFam);
  static const IconData subway = const IconData(0xeb29, fontFamily: _kFontFam);
  static const IconData supervisor_account =
      const IconData(0xeb2a, fontFamily: _kFontFam);
  static const IconData surround_sound =
      const IconData(0xeb2b, fontFamily: _kFontFam);
  static const IconData swap_calls =
      const IconData(0xeb2c, fontFamily: _kFontFam);
  static const IconData swap_horiz =
      const IconData(0xeb2d, fontFamily: _kFontFam);
  static const IconData swap_vert =
      const IconData(0xeb2e, fontFamily: _kFontFam);
  static const IconData swap_vertical_circle =
      const IconData(0xeb2f, fontFamily: _kFontFam);
  static const IconData switch_camera =
      const IconData(0xeb30, fontFamily: _kFontFam);
  static const IconData switch_video =
      const IconData(0xeb31, fontFamily: _kFontFam);
  static const IconData sync_icon =
      const IconData(0xeb32, fontFamily: _kFontFam);
  static const IconData sync_disabled =
      const IconData(0xeb33, fontFamily: _kFontFam);
  static const IconData sync_problem =
      const IconData(0xeb34, fontFamily: _kFontFam);
  static const IconData system_update =
      const IconData(0xeb35, fontFamily: _kFontFam);
  static const IconData system_update_alt =
      const IconData(0xeb36, fontFamily: _kFontFam);
  static const IconData tab = const IconData(0xeb37, fontFamily: _kFontFam);
  static const IconData tab_unselected =
      const IconData(0xeb38, fontFamily: _kFontFam);
  static const IconData tablet = const IconData(0xeb39, fontFamily: _kFontFam);
  static const IconData tablet_android =
      const IconData(0xeb3a, fontFamily: _kFontFam);
  static const IconData tablet_mac =
      const IconData(0xeb3b, fontFamily: _kFontFam);
  static const IconData tag_faces =
      const IconData(0xeb3c, fontFamily: _kFontFam);
  static const IconData tap_and_play =
      const IconData(0xeb3d, fontFamily: _kFontFam);
  static const IconData terrain = const IconData(0xeb3e, fontFamily: _kFontFam);
  static const IconData text_fields =
      const IconData(0xeb3f, fontFamily: _kFontFam);
  static const IconData text_format =
      const IconData(0xeb40, fontFamily: _kFontFam);
  static const IconData textsms = const IconData(0xeb41, fontFamily: _kFontFam);
  static const IconData texture = const IconData(0xeb42, fontFamily: _kFontFam);
  static const IconData theaters =
      const IconData(0xeb43, fontFamily: _kFontFam);
  static const IconData thumb_down =
      const IconData(0xeb44, fontFamily: _kFontFam);
  static const IconData thumb_up =
      const IconData(0xeb45, fontFamily: _kFontFam);
  static const IconData thumbs_up_down =
      const IconData(0xeb46, fontFamily: _kFontFam);
  static const IconData time_to_leave =
      const IconData(0xeb47, fontFamily: _kFontFam);
  static const IconData timelapse =
      const IconData(0xeb48, fontFamily: _kFontFam);
  static const IconData timeline =
      const IconData(0xeb49, fontFamily: _kFontFam);
  static const IconData timer = const IconData(0xeb4a, fontFamily: _kFontFam);
  static const IconData timer_10 =
      const IconData(0xeb4b, fontFamily: _kFontFam);
  static const IconData timer_3 = const IconData(0xeb4c, fontFamily: _kFontFam);
  static const IconData timer_off =
      const IconData(0xeb4d, fontFamily: _kFontFam);
  static const IconData title = const IconData(0xeb4e, fontFamily: _kFontFam);
  static const IconData toc = const IconData(0xeb4f, fontFamily: _kFontFam);
  static const IconData today = const IconData(0xeb50, fontFamily: _kFontFam);
  static const IconData toll = const IconData(0xeb51, fontFamily: _kFontFam);
  static const IconData tonality =
      const IconData(0xeb52, fontFamily: _kFontFam);
  static const IconData touch_app =
      const IconData(0xeb53, fontFamily: _kFontFam);
  static const IconData toys = const IconData(0xeb54, fontFamily: _kFontFam);
  static const IconData track_changes =
      const IconData(0xeb55, fontFamily: _kFontFam);
  static const IconData traffic = const IconData(0xeb56, fontFamily: _kFontFam);
  static const IconData train = const IconData(0xeb57, fontFamily: _kFontFam);
  static const IconData tram = const IconData(0xeb58, fontFamily: _kFontFam);
  static const IconData transfer_within_a_station =
      const IconData(0xeb59, fontFamily: _kFontFam);
  static const IconData transform =
      const IconData(0xeb5a, fontFamily: _kFontFam);
  static const IconData translate =
      const IconData(0xeb5b, fontFamily: _kFontFam);
  static const IconData trending_down =
      const IconData(0xeb5c, fontFamily: _kFontFam);
  static const IconData trending_flat =
      const IconData(0xeb5d, fontFamily: _kFontFam);
  static const IconData trending_up =
      const IconData(0xeb5e, fontFamily: _kFontFam);
  static const IconData tune = const IconData(0xeb5f, fontFamily: _kFontFam);
  static const IconData turned_in =
      const IconData(0xeb60, fontFamily: _kFontFam);
  static const IconData turned_in_not =
      const IconData(0xeb61, fontFamily: _kFontFam);
  static const IconData tv = const IconData(0xeb62, fontFamily: _kFontFam);
  static const IconData unarchive =
      const IconData(0xeb63, fontFamily: _kFontFam);
  static const IconData undo = const IconData(0xeb64, fontFamily: _kFontFam);
  static const IconData unfold_less =
      const IconData(0xeb65, fontFamily: _kFontFam);
  static const IconData unfold_more =
      const IconData(0xeb66, fontFamily: _kFontFam);
  static const IconData update = const IconData(0xeb67, fontFamily: _kFontFam);
  static const IconData usb = const IconData(0xeb68, fontFamily: _kFontFam);
  static const IconData verified_user =
      const IconData(0xeb69, fontFamily: _kFontFam);
  static const IconData vertical_align_bottom =
      const IconData(0xeb6a, fontFamily: _kFontFam);
  static const IconData vertical_align_center =
      const IconData(0xeb6b, fontFamily: _kFontFam);
  static const IconData vertical_align_top =
      const IconData(0xeb6c, fontFamily: _kFontFam);
  static const IconData vibration =
      const IconData(0xeb6d, fontFamily: _kFontFam);
  static const IconData video_call =
      const IconData(0xeb6e, fontFamily: _kFontFam);
  static const IconData video_label =
      const IconData(0xeb6f, fontFamily: _kFontFam);
  static const IconData video_library =
      const IconData(0xeb70, fontFamily: _kFontFam);
  static const IconData videocam =
      const IconData(0xeb71, fontFamily: _kFontFam);
  static const IconData videocam_off =
      const IconData(0xeb72, fontFamily: _kFontFam);
  static const IconData videogame_asset =
      const IconData(0xeb73, fontFamily: _kFontFam);
  static const IconData view_agenda =
      const IconData(0xeb74, fontFamily: _kFontFam);
  static const IconData view_array =
      const IconData(0xeb75, fontFamily: _kFontFam);
  static const IconData view_carousel =
      const IconData(0xeb76, fontFamily: _kFontFam);
  static const IconData view_column =
      const IconData(0xeb77, fontFamily: _kFontFam);
  static const IconData view_comfy =
      const IconData(0xeb78, fontFamily: _kFontFam);
  static const IconData view_compact =
      const IconData(0xeb79, fontFamily: _kFontFam);
  static const IconData view_day =
      const IconData(0xeb7a, fontFamily: _kFontFam);
  static const IconData view_headline =
      const IconData(0xeb7b, fontFamily: _kFontFam);
  static const IconData view_list =
      const IconData(0xeb7c, fontFamily: _kFontFam);
  static const IconData view_module =
      const IconData(0xeb7d, fontFamily: _kFontFam);
  static const IconData view_quilt =
      const IconData(0xeb7e, fontFamily: _kFontFam);
  static const IconData view_stream =
      const IconData(0xeb7f, fontFamily: _kFontFam);
  static const IconData view_week =
      const IconData(0xeb80, fontFamily: _kFontFam);
  static const IconData vignette =
      const IconData(0xeb81, fontFamily: _kFontFam);
  static const IconData visibility =
      const IconData(0xeb82, fontFamily: _kFontFam);
  static const IconData visibility_off =
      const IconData(0xeb83, fontFamily: _kFontFam);
  static const IconData voice_chat =
      const IconData(0xeb84, fontFamily: _kFontFam);
  static const IconData voicemail =
      const IconData(0xeb85, fontFamily: _kFontFam);
  static const IconData volume_down =
      const IconData(0xeb86, fontFamily: _kFontFam);
  static const IconData volume_mute =
      const IconData(0xeb87, fontFamily: _kFontFam);
  static const IconData volume_off =
      const IconData(0xeb88, fontFamily: _kFontFam);
  static const IconData volume_up =
      const IconData(0xeb89, fontFamily: _kFontFam);
  static const IconData vpn_key = const IconData(0xeb8a, fontFamily: _kFontFam);
  static const IconData vpn_lock =
      const IconData(0xeb8b, fontFamily: _kFontFam);
  static const IconData wallpaper =
      const IconData(0xeb8c, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xeb8d, fontFamily: _kFontFam);
  static const IconData watch = const IconData(0xeb8e, fontFamily: _kFontFam);
  static const IconData watch_later =
      const IconData(0xeb8f, fontFamily: _kFontFam);
  static const IconData wb_auto = const IconData(0xeb90, fontFamily: _kFontFam);
  static const IconData wb_cloudy =
      const IconData(0xeb91, fontFamily: _kFontFam);
  static const IconData wb_incandescent =
      const IconData(0xeb92, fontFamily: _kFontFam);
  static const IconData wb_iridescent =
      const IconData(0xeb93, fontFamily: _kFontFam);
  static const IconData wb_sunny =
      const IconData(0xeb94, fontFamily: _kFontFam);
  static const IconData wc = const IconData(0xeb95, fontFamily: _kFontFam);
  static const IconData web = const IconData(0xeb96, fontFamily: _kFontFam);
  static const IconData web_asset =
      const IconData(0xeb97, fontFamily: _kFontFam);
  static const IconData weekend = const IconData(0xeb98, fontFamily: _kFontFam);
  static const IconData whatshot =
      const IconData(0xeb99, fontFamily: _kFontFam);
  static const IconData widgets = const IconData(0xeb9a, fontFamily: _kFontFam);
  static const IconData wifi = const IconData(0xeb9b, fontFamily: _kFontFam);
  static const IconData wifi_lock =
      const IconData(0xeb9c, fontFamily: _kFontFam);
  static const IconData wifi_tethering =
      const IconData(0xeb9d, fontFamily: _kFontFam);
  static const IconData work = const IconData(0xeb9e, fontFamily: _kFontFam);
  static const IconData wrap_text =
      const IconData(0xeb9f, fontFamily: _kFontFam);
  static const IconData youtube_searched_for =
      const IconData(0xeba0, fontFamily: _kFontFam);
  static const IconData zoom_in = const IconData(0xeba1, fontFamily: _kFontFam);
  static const IconData zoom_out =
      const IconData(0xeba2, fontFamily: _kFontFam);
  static const IconData zoom_out_map =
      const IconData(0xeba3, fontFamily: _kFontFam);
  static const IconData account_balance_wallet =
      const IconData(0xf008, fontFamily: _kFontFam);
}
